apiVersion: apps/v1
kind: Deployment
metadata:
  name: testhtml
  namespace: mark-k8s-dev
  labels:
    app: testhtml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testhtml
  template:
    metadata:
      labels:
        app: testhtml
    spec:
      containers:
        - name: testhtml
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              subPath: "nginx-html/testhtml" #文件路径,以挂载的pvc为基准
              name: testhtml-data
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: NGINX_PORT
              value: "80"

      volumes:
        - name: testhtml-data
          persistentVolumeClaim:
            claimName: gluster-claim-pub
